services:
  - type: web
    runtime: static
    name: sitevantage
    branch: main
    buildCommand: npm run build
    staticPublishPath: ./dist
    autoDeployTrigger: commit
    headers:
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
